# -*- coding: utf-8 -*-
"""TensorFlow Test #1 (MNIST)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4fk6Kkv9pQDYV_a2rXHHcmTesI6LY89
"""

import tensorflow as tf
import tensorflow.keras.layers as layers

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

model = tf.keras.models.Sequential([
      layers.Flatten(input_shape=(28,28)),
      layers.Dense(128, activation='relu'),
      layers.Dropout(0.2),
      layers.Dense(10)
])

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5)

model.evaluate(x_test,y_test,verbose=2)

prob_model = tf.keras.Sequential([
        model,
        layers.Softmax()
])

print(y_test[:2])
model(x_test[:,2])
prob_model(x_test[:2])
